---
# tasks file for ./roles/build_iso
- name: Create blueprint
  when: not skip_blueprint_creation | bool
  become: yes
  ansible.builtin.import_tasks: create_blueprint.yml

- name: Compose image installer
  when: not skip_compose | bool
  become: yes
  ansible.builtin.import_tasks: compose.yml

- name: Download artifact
  when: compose_job_id != ""
  become: yes
  ansible.builtin.import_tasks: download_artifact.yml

- name: Create custom iso
  when: compose_job_id != ""
  become: yes
  ansible.builtin.import_tasks: create_custom_iso.yml
