---
# defaults file for ./roles/create_windows_vm
# Virtual machine default
vm_name: winhmi
vm_memory: 16000
vm_vcpus: 4

# disk image, be sure to create this with windows 11 pro 
# installed and configured copy it to host machine
qcow2_disk_image: winhmi_disk.qcow2
disk_size: 128

# User defaults
admin_user: admin
organization: redhat
windows_license_key: "00000-00000-00000-00000-00000"

# networking settings
networking:
  ip4: 172.16.20.10
  subnetmask: 255.255.255.0
  gw4: 172.16.20.1

locale_settings:
  input: en-US
  system: en-US
  uilang: en-US
  user: en-US
  
# Software directory
software_dir: /home/software

# libvirt images directory
libvirt_images_dir: /vms