---
# tasks file for ./roles/customize_iso
- name: Download artifact
  when: compose_job_id != ""
  become: yes
  ansible.builtin.import_tasks: download_artifact.yml

- name: Create custom iso
  when: compose_job_id != ""
  become: yes
  ansible.builtin.import_tasks: create_custom_iso.yml
