---
# tasks file for ./roles/install_aap
- name: Preflight steps
  ansible.builtin.import_tasks: preflight.yml

- name: Download installer bundle
  ansible.builtin.import_tasks: download_aap_installer.yml

- name: Install AAP
  ansible.builtin.import_tasks: install_aap.yml