---
# reused from https://github.com/kwozyman/vpac
- name: Ensure virt rpm packages exist
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - libvirt
    - virt-install
    - virt-viewer

- name: Ensure vm path exists
  ansible.builtin.file:
    path: "{{ ssc600_vm.path }}"
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX

- name: Write the libvirt xml template
  ansible.builtin.template:
    src: libvirt-domain.xml.j2
    dest: "{{ ssc600_vm.path }}/{{ ssc600_vm.name }}.xml"
    owner: root
    group: root
    mode: u=rw,g=r,0=r

- name: Write the virtual network xml template
  ansible.builtin.template:
    src: libvirt-network.xml.j2
    dest: "{{ ssc600_vm.path }}/station-bus-vnet.xml"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Copy ABB disk image
  ansible.builtin.copy:
    src: "{{ ssc600_bundle.extracted_path }}/virtual_products/ssc600_disk.img"
    dest: "{{ ssc600_vm.path }}/{{ ssc600_vm.name }}.img"
    owner: root
    group: root
    mode: u=rw,g=r,0=r
    remote_src: true

- name: Ensure libvirt directory exists
  ansible.builtin.file:
    path: /etc/libvirt/hooks
    state: directory
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX

- name: Setup qemu hook
  ansible.builtin.template:
    src: qemu.hook.j2
    dest: /etc/libvirt/hooks/qemu
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Make sure libvirtd is up
  ansible.builtin.service:
    name: libvirtd
    state: restarted
    enabled: true

- name: Setup station bus virtual network
  community.libvirt.virt_net:
    command: define
    name: station-bus-vnet
    xml: "{{ lookup('template', 'libvirt-network.xml.j2') }}"
    autostart: true

- name: Setup libvirt domain
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'libvirt-domain.xml.j2')}}"
    autostart: true